version: '3.8'

services:
  bot_image:
    env_file:
      - .env
    networks:
      - botnet
    build: ./bot
    depends_on:
      - db_image
      - db_repl_image

  db_image:
    env_file:
      - .env
    networks:
      - botnet
    restart: always
    healthcheck:
      test: 'pg_isready -U postgres --dbname=${DB_DATABASE}'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
      - 2334:22
    build: 
      context: ./db
      args:
        - RM_USER=$RM_USER
        - RM_PASSWORD=$RM_PASSWORD

  db_repl_image:
    env_file:
      - .env
    environment:
      - PGUSER=$DB_REPL_USER
      - PGPASSWORD=$DB_REPL_PASSWORD
      - POSTGRES_PASSWORD=$DB_REPL_PASSWORD
    networks:
      - botnet
    restart: always
    healthcheck:
      test: 'pg_isready -U postgres --dbname=${DB_DATABASE}'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    build: ./replication

networks:
  botnet:
    ipam:
      config:
        - subnet: 172.10.1.0/24
